version: '3.8'

services:
  chitchat_fe_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ./src:/user/src/app/src