import { baseApiWithGraphql } from "./baseApi";


export const injectedRtkApi = baseApiWithGraphql.injectEndpoints({
  endpoints: (build) => ({
    TestQuery: build.query({
      query: (variables) => ({
        document: `query TestQuery {
        testQuery {
            _id
            email
            tags
            status
            user {
                username
                firstname
            }
        }
    }`,
        variables: variables || {},  // Ensure variables are passed as an object, even if empty
      }),
    }),
  }),
});

// Export hooks for usage in function components, which are auto-generated by the `injectEndpoints` method
export const { useTestQueryQuery } = injectedRtkApi;
